[project]
name = "scint"
version = "0.5.0"
description = "Add your description here"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT License" }
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.10.10",
    "anthropic>=0.39.0",
    "meilisearch-python-sdk>=3.6.1",
    "meilisearch>=0.31.6",
    "openai>=1.55.2",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.2",
    "redis>=5.2.0",
    "tree-sitter>=0.23.2",
    "tree-sitter-python>=0.23.3",
    "uvicorn>=0.32.0",
    "chonkie>=0.1.2",
    "numpy>=2.1.3",
    "ruff>=0.8.0",
    "rich>=13.9.4",
    "nltk>=3.9.1",
    "websockets>=14.1",
    "jinja2>=3.1.5",
    "networkx>=3.4.2",
    "matplotlib>=3.10.0",
    "fastapi>=0.115.8",
    "sentence-transformers>=3.4.1",
    "base32-lib>=1.0.2",
    "surrealdb>=1.0.3",
    "pyvis>=0.3.2",
    "pypdf2>=3.0.1",
    "bs4>=0.0.2",
]

[tool.setuptools]
package-dir = {"scint" = "scint"}

[tool.pytest]
testpaths = ["tests"]
addopts = "--import-mode=importlib"
pythonpath = ["."]

[tool.pyright]
venvPath = ".venv"
venv = "."
reportMissingImports = true
reportSyntaxErrors = true
reportMissingTypeStubs = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = "none"
reportMissingModuleSource = true
reportGeneralTypeIssues = false
typeCheckingMode = "off"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
